name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: corepack enable

      - name: Get yarn cache directory path
        id: cache-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.cache-path.outputs.dir }}
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Typecheck
        run: yarn typecheck

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: corepack enable

      - name: Get yarn cache directory path
        id: cache-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.cache-path.outputs.dir }}
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: corepack enable

      - name: Get yarn cache directory path
        id: cache-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.cache-path.outputs.dir }}
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn test
